# Generated by Django 5.2.3 on 2025-06-17 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0003_regiontypes_alter_regions_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiontypes',
            options={'managed': True, 'ordering': ['id'], 'verbose_name': 'Тип региона', 'verbose_name_plural': 'Типы регионов'},
        ),
        migrations.AlterModelTable(
            name='regiontypes',
            table='region_types',
        ),
    ]
