# Generated by Django 5.2.3 on 2025-06-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0011_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Подтверждено', 'Подтверждено'), ('Отклонено', 'Отклонено')], max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
