# Generated by Django 5.2.3 on 2025-06-22 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0018_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservices',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='booking_serv', to='celebration_project.booking', verbose_name='Аренда'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('zone', 'date'), name='unique_booking_per_zone_per_date'),
        ),
    ]
