# Generated by Django 5.2.3 on 2025-06-22 14:25

import celebration_project.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0019_alter_bookingservices_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=celebration_project.models.UnsignedIntegerField(blank=True, null=True, verbose_name='Кол-во человек'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='people',
            field=celebration_project.models.UnsignedIntegerField(verbose_name='Кол-во человек'),
        ),
    ]
