# Generated by Django 5.2.3 on 2025-06-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0021_alter_locations_max_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price_type',
            field=models.CharField(choices=[('per_person', 'Р/чел'), ('per_day', 'Р/сутки'), ('per_hour', 'Р/час'), ('taxi', 'Такси (50р + 10р/км)')], default='per_day', max_length=20, verbose_name='Тип расчета'),
        ),
    ]
