# Generated by Django 5.2.3 on 2025-06-14 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Итоговая цена')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('people', models.SmallIntegerField(verbose_name='Кол-во человек')),
                ('status', models.CharField(choices=[('Подтверждено', 'Подтверждено'), ('Отклонено', 'Отклонено')], max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'booking',
                'ordering': ['id', '-total_price'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sales/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'db_table': 'sales',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
                'ordering': ['-cost', 'id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.IntegerField(verbose_name='Дом')),
                ('index', models.CharField(blank=True, max_length=1, null=True, verbose_name='Индекс')),
                ('max_people', models.SmallIntegerField(verbose_name='Максимальное кол-во человек')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='celebration_project.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'locations',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingServices',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='celebration_project.booking', verbose_name='Аренда')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='celebration_project.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в бронировании',
                'verbose_name_plural': 'Услуги в бронировании',
                'db_table': 'booking_services',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_services',
            field=models.ManyToManyField(blank=True, related_name='booking_services', through='celebration_project.BookingServices', to='celebration_project.services'),
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_num', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
                'db_table': 'user_information',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.DO_NOTHING, to='celebration_project.userinformation', verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('people', models.SmallIntegerField(verbose_name='Кол-во человек')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='celebration_project.locations', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
                'db_table': 'zones',
                'ordering': ['id', '-price'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='celebration_project.zones', verbose_name='Зона'),
        ),
    ]
