# Generated by Django 5.2.3 on 2025-06-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zones',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zones',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конечное время'),
        ),
        migrations.AddField(
            model_name='zones',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начальное время'),
        ),
    ]
