# Generated by Django 5.2.3 on 2025-06-17 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0002_zones_description_zones_end_time_zones_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Тип')),
            ],
        ),
        migrations.AlterField(
            model_name='regions',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='celebration_project.regiontypes', verbose_name='Тип'),
        ),
    ]
