# Generated by Django 5.2.3 on 2025-06-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0004_alter_regiontypes_options_alter_regiontypes_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='План'),
        ),
        migrations.AddField(
            model_name='zones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='zones/', verbose_name='Изображение'),
        ),
    ]
