# Generated by Django 5.2.3 on 2025-06-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0006_locations_name_alter_zones_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='plan',
        ),
        migrations.AddField(
            model_name='locations',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='zones',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='zones/plan', verbose_name='План'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='zones/image', verbose_name='Изображение'),
        ),
    ]
