# Generated by Django 5.2.3 on 2025-06-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0007_remove_locations_plan_locations_photo_zones_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
    ]
