# Generated by Django 5.2.3 on 2025-06-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0008_locations_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='zones/', verbose_name='Изображение'),
        ),
    ]
