# Generated by Django 5.2.3 on 2025-06-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0010_remove_booking_client_booking_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
