# Generated by Django 5.2.3 on 2025-06-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='location', to='celebration_project.regions', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='zone', to='celebration_project.locations', verbose_name='Локация'),
        ),
    ]
