# Generated by Django 5.2.3 on 2025-06-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0014_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Кол-во человек'),
        ),
    ]
