# Generated by Django 5.2.3 on 2025-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0016_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Подтверждено', 'Подтверждено'), ('Отклонено', 'Отклонено'), ('Ожидание', 'Ожидание')], max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
