# Generated by Django 5.2.3 on 2025-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0017_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Подтверждено', 'Подтверждено'), ('Отклонено', 'Отклонено'), ('Ожидание', 'Ожидание')], default='Ожидание', max_length=50, verbose_name='Статус'),
        ),
    ]
