# Generated by Django 5.2.3 on 2025-06-22 14:27

import celebration_project.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0020_alter_booking_people_alter_zones_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='max_people',
            field=celebration_project.models.UnsignedIntegerField(verbose_name='Максимальное кол-во человек'),
        ),
    ]
