# Generated by Django 5.2.3 on 2025-06-22 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0022_services_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservices',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_serv', to='celebration_project.booking', verbose_name='Аренда'),
        ),
    ]
