# Generated by Django 5.2.3 on 2025-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration_project', '0023_alter_bookingservices_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
